name: Convert to HEVC with Custom Options

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct URL of the video to process'
        required: true
      quality:
        description: 'Output quality: preserve, 720p, 1080p, or 4K'
        required: true
        default: 'preserve'
      fps:
        description: 'Frame rate for output video (24, 30, or 60)'
        required: true
        default: '60'
      hevc_crf:
        description: 'CRF value for HEVC encoding'
        required: true
        default: '33'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          echo "Downloading video from '${{ github.event.inputs.video_url }}'"
          curl -L "${{ github.event.inputs.video_url }}" -o input_video

      - name: Convert to MP4 (Always)
        run: |
          echo "Re-encoding video to MP4..."
          # Determine scaling filter based on quality input
          if [ "${{ github.event.inputs.quality }}" = "preserve" ]; then
            SCALE=""
          elif [ "${{ github.event.inputs.quality }}" = "720p" ]; then
            SCALE=",scale=-2:720"
          elif [ "${{ github.event.inputs.quality }}" = "1080p" ]; then
            SCALE=",scale=-2:1080"
          elif [ "${{ github.event.inputs.quality }}" = "4K" ]; then
            SCALE=",scale=-2:2160"
          else
            SCALE=""
          fi
          ffmpeg -i input_video -vf "minterpolate=fps=${{ github.event.inputs.fps }}:mi_mode=mci:mc_mode=aobmc:me_mode=bidir${SCALE}" -c:v libx264 -crf 28 -preset veryslow -c:a aac -b:a 128k mp4_video.mp4

      - name: Convert MP4 to HEVC (H.265)
        run: |
          echo "Converting MP4 to HEVC..."
          if [ "${{ github.event.inputs.quality }}" = "preserve" ]; then
            SCALE=""
          elif [ "${{ github.event.inputs.quality }}" = "720p" ]; then
            SCALE=",scale=-2:720"
          elif [ "${{ github.event.inputs.quality }}" = "1080p" ]; then
            SCALE=",scale=-2:1080"
          elif [ "${{ github.event.inputs.quality }}" = "4K" ]; then
            SCALE=",scale=-2:2160"
          else
            SCALE=""
          fi
          ffmpeg -i mp4_video.mp4 -vf "minterpolate=fps=${{ github.event.inputs.fps }}:mi_mode=mci:mc_mode=aobmc:me_mode=bidir${SCALE}" -c:v libx265 -crf ${{ github.event.inputs.hevc_crf }} -preset veryslow -c:a aac -b:a 128k hevc_video_${{ github.event.inputs.fps }}fps.mp4

      - name: Upload HEVC Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hevc_video_${{ github.event.inputs.fps }}fps
          path: hevc_video_${{ github.event.inputs.fps }}fps.mp4
