name: Convert to HEVC 60fps

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Direct URL of the video to process'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          echo "Downloading video from '${{ github.event.inputs.video_url }}'"
          curl -L "${{ github.event.inputs.video_url }}" -o input_video

      - name: Convert to MP4 (Always)
        run: |
          echo "Re-encoding video to MP4..."
          ffmpeg -i input_video -vf "minterpolate=fps=60:mi_mode=mci:mc_mode=aobmc:me_mode=bidir" -c:v libx264 -crf 28 -preset veryslow -c:a aac -b:a 128k mp4_video.mp4

      - name: Convert MP4 to HEVC (H.265)
        run: |
          echo "Converting MP4 to HEVC..."
          ffmpeg -i mp4_video.mp4 -vf "minterpolate=fps=60:mi_mode=mci:mc_mode=aobmc:me_mode=bidir" -c:v libx265 -crf 33 -preset veryslow -c:a aac -b:a 128k hevc_video_60fps.mp4

      - name: Upload HEVC Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hevc_video_60fps
          path: hevc_video_60fps.mp4
