name: Mega to Archive.org 

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        # Installs the latest version of rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Install megacmd
        # Installs the official MEGA command-line tool on the runner
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          # Using the package for Ubuntu 22.04, which is the base for the latest GitHub runners
          wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb
          sudo apt install -y ./megacmd-xUbuntu_22.04_amd64.deb

      - name: Login to Mega
        # Logs into Mega using credentials stored in GitHub secrets
        env:
          MEGA_EMAIL: ${{ secrets.MEGA_EMAIL }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
        run: |
          mega-login "$MEGA_EMAIL" "$MEGA_PASSWORD"

      - name: Import Mega Link and Serve as WebDAV
        # Create a directory, import the link, and serve the ENTIRE account root (/) via WebDAV.
        # This is more stable than serving a sub-directory.
        run: |
          mega-mkdir /imported-from-mega
          mega-import 'https://mega.nz/folder/6uwARLIS#pjaTvXrkmBTkaE0b5czHBA' /imported-from-mega
          mega-webdav / --port=4443 --public &
          sleep 5 # Give the server a moment to initialize

      - name: Configure rclone and Upload to Archive.org
        # Sets up rclone configuration using environment variables and then runs the copy command.
        # This step now includes obscuring the password for the WebDAV remote.
        env:
          # WebDAV remote configuration (password will be set in the run step)
          RCLONE_CONFIG_WEBDAV_TYPE: webdav
          RCLONE_CONFIG_WEBDAV_URL: http://127.0.0.1:4443
          RCLONE_CONFIG_WEBDAV_VENDOR: other
          RCLONE_CONFIG_WEBDAV_USER: ${{ secrets.MEGA_EMAIL }}
          MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}

          # Internet Archive remote configuration using secrets
          RCLONE_CONFIG_ARCHIVE_TYPE: internetarchive
          RCLONE_CONFIG_ARCHIVE_ACCESS_KEY_ID: ${{ secrets.IA_ACCESS_KEY }}
          RCLONE_CONFIG_ARCHIVE_SECRET_ACCESS_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: |
          # Obscure the password for rclone and export it to the environment
          OBSCURED_PASS=$(rclone obscure "$MEGA_PASSWORD")
          export RCLONE_CONFIG_WEBDAV_PASS="$OBSCURED_PASS"

          echo "Rclone configuration is set via environment variables. Verifying remotes:"
          rclone config show
          
          echo "Starting upload to Archive.org..."
          # Copies files from the 'imported-from-mega' directory on the WebDAV remote
          # to the specified existing Archive.org item
          rclone copy webdav:imported-from-mega/ archive:gdrive-upload-16031443727-1/ --progress
