name: Mega to Archive.org

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        # Installs the latest version of rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Install megacmd
        # Installs the official MEGA command-line tool on the runner
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          # Using the package for Ubuntu 22.04, which is the base for the latest GitHub runners
          wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb
          sudo apt install -y ./megacmd-xUbuntu_22.04_amd64.deb

      - name: Serve Mega folder as WebDAV
        # Starts a WebDAV server in the background to serve the public Mega folder
        # This makes the public, non-owned folder accessible to rclone
        run: |
          mega-webdav --public-url="https://mega.nz/folder/6uwARLIS#pjaTvXrkmBTkaE0b5czHBA" --port=4443 &
          sleep 5 # Give the server a moment to initialize

      - name: Configure rclone
        # Sets up rclone configuration using environment variables for security
        # No config file is written to disk
        env:
          # WebDAV remote configuration pointing to the local megacmd server
          RCLONE_CONFIG_WEBDAV_TYPE: webdav
          RCLONE_CONFIG_WEBDAV_URL: http://127.0.0.1:4443
          RCLONE_CONFIG_WEBDAV_VENDOR: other

          # Internet Archive remote configuration using secrets
          RCLONE_CONFIG_ARCHIVE_TYPE: internetarchive
          RCLONE_CONFIG_ARCHIVE_ACCESS_KEY_ID: ${{ secrets.IA_ACCESS_KEY }}
          RCLONE_CONFIG_ARCHIVE_SECRET_ACCESS_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: |
          echo "Rclone configuration is set via environment variables."
          rclone config show

      - name: Upload to existing Archive.org item
        # Copies all files and folders from the WebDAV source (Mega folder)
        # to the specified existing Archive.org item
        run: |
          rclone copy webdav: archive:gdrive-upload-16031443727-1/ --progress
