name: Google Drive to Archive.org Uploader

# This action is triggered manually from the GitHub Actions tab.
on:
  workflow_dispatch:
    inputs:
      google_drive_url:
        description: 'The full URL of the public Google Drive folder or file'
        required: true
        type: string
      archive_identifier:
        description: 'Unique ID for the Archive.org item (leave blank to auto-generate)'
        required: false
        type: string
      archive_title:
        description: 'Page Title for the Archive.org item'
        required: true
        type: string
      archive_mediatype:
        description: 'Select the media type for the item'
        required: true
        type: choice
        options:
        - texts
        - audio
        - movies
        - software
        - image
        - data
        default: 'texts'
      archive_description:
        description: 'A description of the item page'
        required: false
        type: string
      archive_subjects:
        description: 'Keywords, separated by commas (e.g., data, backup, files)'
        required: false
        type: string
      archive_creator:
        description: 'Creator of the content'
        required: false
        type: string
      archive_date:
        description: 'Date work was created/published (YYYY-MM-DD)'
        required: false
        type: string
      archive_test_item:
        description: 'Is this a test item?'
        required: true
        type: choice
        options:
        - 'No'
        - 'Yes (will be removed after 30 days)'
        default: 'No'
      archive_license:
        description: 'Select a license for the item'
        required: true
        type: choice
        options:
        - 'Leave license blank'
        - 'CC0 - "No Rights Reserved"'
        - 'Public Domain Mark 1.0'
        - 'Creative Commons Attribution 4.0'
        - 'Creative Commons Attribution-ShareAlike 4.0'
        - 'Creative Commons Attribution-NonCommercial 4.0'
        - 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0'
        default: 'Leave license blank'

jobs:
  upload-to-archive:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Dependencies (rclone, internetarchive)
      - name: Install Dependencies
        run: |
          curl https://rclone.org/install.sh | sudo bash
          python -m pip install --upgrade pip
          pip install internetarchive

      # Step 3: Decode rclone config from Base64 secret
      - name: Create rclone config from secret
        run: |
          echo "${{ secrets.RCLONE_CONF }}" | base64 --decode > rclone.conf

      # Step 4: Create a directory to hold the downloaded files
      - name: Create download directory
        run: mkdir gdrive_files

      # Step 5: Download from Google Drive (handles folder and file URLs)
      - name: Download from Google Drive
        run: |
          URL="${{ github.event.inputs.google_drive_url }}"
          
          if [[ $URL == *"/folders/"* ]]; then
            # Extract Folder ID from URL
            FOLDER_ID=$(echo "$URL" | sed -n 's|.*/folders/\([^/?]*\).*|\1|p')
            echo "--- Downloading from Folder ID: $FOLDER_ID ---"
            rclone copy gdrive: gdrive_files/ \
              --config ./rclone.conf \
              --drive-root-folder-id "$FOLDER_ID" \
              -P
          elif [[ $URL == *"/file/d/"* ]]; then
            # Extract File ID from URL
            FILE_ID=$(echo "$URL" | sed -n 's|.*/d/\([^/?]*\).*|\1|p')
            echo "--- Downloading from File ID: $FILE_ID ---"
            
            # Construct the direct download URL for the file.
            DOWNLOAD_URL="https://drive.google.com/uc?export=download&id=${FILE_ID}"
            
            # Use rclone copyurl, which is designed for downloading from a URL.
            # This is the most reliable method for single files.
            rclone copyurl "$DOWNLOAD_URL" gdrive_files/ \
              --config ./rclone.conf \
              -P
          else
            echo "--- ERROR: Invalid Google Drive URL format. Please provide a valid file or folder link. ---"
            exit 1
          fi

      # Step 6: Create local Archive.org config file
      - name: Create local Archive.org config file
        run: |
          echo "[s3]" > ia.cfg
          echo "access = ${{ secrets.IA_ACCESS_KEY }}" >> ia.cfg
          echo "secret = ${{ secrets.IA_SECRET_KEY }}" >> ia.cfg

      # Step 7: Prepare subject tags for the upload command
      - name: Prepare Subject Tags
        run: |
          tags="${{ github.event.inputs.archive_subjects }}"
          echo "formatted_tags=${tags//,/;}" >> $GITHUB_ENV

      # Step 8: Set Archive.org Identifier (use default if blank)
      - name: Set Archive.org Identifier
        run: |
          if [[ -z "${{ github.event.inputs.archive_identifier }}" ]]; then
            echo "Identifier is blank, creating a default ID."
            echo "ARCHIVE_ID_FINAL=gdrive-upload-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
          else
            echo "Using user-provided identifier."
            echo "ARCHIVE_ID_FINAL=${{ github.event.inputs.archive_identifier }}" >> $GITHUB_ENV
          fi

      # Step 9: Build and execute the upload command
      - name: Upload files to Archive.org
        run: |
          # Determine the correct collection based on the mediatype
          MEDIATYPE="${{ github.event.inputs.archive_mediatype }}"
          if [[ "$MEDIATYPE" == "data" ]]; then
            ARCHIVE_COLLECTION="opensource_media"
          elif [[ "$MEDIATYPE" == "texts" ]]; then
            ARCHIVE_COLLECTION="opensource"
          else
            ARCHIVE_COLLECTION="opensource_$MEDIATYPE"
          fi

          # Start with the base command and required metadata
          CMD="ia --config-file ./ia.cfg upload ${{ env.ARCHIVE_ID_FINAL }} gdrive_files/ \
            --metadata=\"title:${{ github.event.inputs.archive_title }}\" \
            --metadata=\"collection:$ARCHIVE_COLLECTION\" \
            --metadata=\"mediatype:$MEDIATYPE\""

          # Add optional text metadata if it exists
          if [[ -n "${{ github.event.inputs.archive_description }}" ]]; then
            CMD="$CMD --metadata=\"description:${{ github.event.inputs.archive_description }}\""
          fi
          if [[ -n "${{ env.formatted_tags }}" ]]; then
            CMD="$CMD --metadata=\"subject:${{ env.formatted_tags }}\""
          fi
          if [[ -n "${{ github.event.inputs.archive_creator }}" ]]; then
            CMD="$CMD --metadata=\"creator:${{ github.event.inputs.archive_creator }}\""
          fi
          if [[ -n "${{ github.event.inputs.archive_date }}" ]]; then
            CMD="$CMD --metadata=\"date:${{ github.event.inputs.archive_date }}\""
          fi

          # Handle Test Item selection
          if [[ "${{ github.event.inputs.archive_test_item }}" == "Yes (will be removed after 30 days)" ]]; then
            CMD="$CMD --metadata=\"test-item:yes\""
          fi

          # Handle License selection
          LICENSE_URL=""
          if [[ "${{ github.event.inputs.archive_license }}" == "CC0 - \"No Rights Reserved\"" ]]; then
            LICENSE_URL="https://creativecommons.org/publicdomain/zero/1.0/"
          elif [[ "${{ github.event.inputs.archive_license }}" == "Public Domain Mark 1.0" ]]; then
            LICENSE_URL="https://creativecommons.org/publicdomain/mark/1.0/"
          elif [[ "${{ github.event.inputs.archive_license }}" == "Creative Commons Attribution 4.0" ]]; then
            LICENSE_URL="https://creativecommons.org/licenses/by/4.0/"
          elif [[ "${{ github.event.inputs.archive_license }}" == "Creative Commons Attribution-ShareAlike 4.0" ]]; then
            LICENSE_URL="https://creativecommons.org/licenses/by-sa/4.0/"
          elif [[ "${{ github.event.inputs.archive_license }}" == "Creative Commons Attribution-NonCommercial 4.0" ]]; then
            LICENSE_URL="https://creativecommons.org/licenses/by-nc/4.0/"
          elif [[ "${{ github.event.inputs.archive_license }}" == "Creative Commons Attribution-NonCommercial-ShareAlike 4.0" ]]; then
            LICENSE_URL="https://creativecommons.org/licenses/by-nc-sa/4.0/"
          fi
          
          if [[ -n "$LICENSE_URL" ]]; then
            CMD="$CMD --metadata=\"licenseurl:$LICENSE_URL\""
          fi

          # Execute the final command
          echo "Executing command..."
          eval $CMD
