name: Upload Google Drive Folder to Archive.org

on:
  workflow_dispatch:
    inputs:
      archive_identifier:
        description: 'Unique ID for the Archive.org item (no spaces)'
        required: true
        type: string
      archive_title:
        description: 'Page Title for the Archive.org item'
        required: true
        type: string
      archive_collection:
        description: 'The collection mediatype (e.g., community, data, software)'
        required: true
        type: string
        default: 'community'
      archive_description:
        description: 'A description of the item page'
        required: false
        type: string
      archive_subjects:
        description: 'Keywords, separated by commas (e.g., data, backup, files)'
        required: false
        type: string
      archive_creator:
        description: 'Creator of the content'
        required: false
        type: string
      archive_date:
        description: 'Date work was created/published (YYYY-MM-DD)'
        required: false
        type: string
      archive_language:
        description: 'Language of the work (3-letter code, e.g., eng)'
        required: false
        type: string

jobs:
  upload-to-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown internetarchive

      - name: Create download directory
        run: mkdir gdrive_files

      - name: Download files from Google Drive
        run: |
          gdown --folder 'https://drive.google.com/drive/folders/1wImUx1UkFVRDB-plqwoGo15blPgXD-Cn' -O gdrive_files

      - name: Configure Archive.org CLI
        run: |
          ia configure --access-key ${{ secrets.IA_ACCESS_KEY }} --secret-key ${{ secrets.IA_SECRET_KEY }}
      
      - name: Prepare Subject Tags
        id: prep_tags
        run: |
          # The 'ia' tool expects semicolons for multiple tags.
          # This replaces commas from the input with semicolons.
          tags="${{ github.event.inputs.archive_subjects }}"
          echo "formatted_tags=${tags//,/;}" >> $GITHUB_ENV

      - name: Upload files to Archive.org
        run: |
          ia upload ${{ github.event.inputs.archive_identifier }} gdrive_files/ \
          --metadata="title:${{ github.event.inputs.archive_title }}" \
          --metadata="collection:${{ github.event.inputs.archive_collection }}" \
          --metadata="description:${{ github.event.inputs.archive_description }}" \
          --metadata="subject:${{ env.formatted_tags }}" \
          --metadata="creator:${{ github.event.inputs.archive_creator }}" \
          --metadata="date:${{ github.event.inputs.archive_date }}" \
          --metadata="language:${{ github.event.inputs.archive_language }}"