# .github/workflows/gdrive_to_archive.yml
name: Upload Google Drive Folder to Archive.org

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow automatically every Sunday at midnight UTC
  schedule:
    - cron: '0 0 * * 0'

jobs:
  upload-to-archive:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository (not strictly necessary for this script, but good practice)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python, which is needed for our command-line tools
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install the necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown internetarchive

      # 4. Download all files from the public Google Drive folder
      - name: Download files from Google Drive
        run: |
          # Create a directory to store the downloaded files
          mkdir gdrive_downloads
          # Use gdown to download the entire folder contents
          gdown --folder https://drive.google.com/drive/folders/1wImUx1UkFVRDB-plqwoGo15blPgXD-Cn -O ./gdrive_downloads

      # 5. (Optional) List downloaded files for debugging purposes
      - name: List downloaded files
        run: |
          echo "The following files were downloaded:"
          ls -R ./gdrive_downloads

      # 6. Upload the downloaded files to Archive.org
      - name: Upload to Archive.org
        # Use environment variables to securely pass your Archive.org keys
        env:
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: |
          # Create a unique identifier for the new item on Archive.org.
          # This uses the Google Drive folder ID and the current date.
          IDENTIFIER="gdrive-archive-1wImUx1UkFVRDB-plqwoGo15blPgXD-Cn-$(date +%Y-%m-%d)"
          echo "Uploading to Archive.org with identifier: $IDENTIFIER"

          # Run the upload command.
          # It uploads all files from the 'gdrive_downloads' directory.
          # We add metadata to make the item findable and descriptive.
          ia upload "$IDENTIFIER" ./gdrive_downloads/* \
            --metadata="title:Automatic Archive of GDrive Folder (1wImUx1UkFVRDB-plqwoGo15blPgXD-Cn)" \
            --metadata="collection:opensource_media" \
            --metadata="subject:gdrive;backup;archive" \
            --metadata="description:This item is an automatic backup of the public Google Drive folder located at https://drive.google.com/drive/folders/1wImUx1UkFVRDB-plqwoGo15blPgXD-Cn. This backup was created by a GitHub Action." \
            --verbose
